### ISSUE TITLE
请问以后会考虑国内期货和期权吗？

### ISSUE THREAD

**Issue by cyzwwszw** [rainx/inside-zipline#3]
请问以后会考虑国内期货和期权吗？

**Comment by rainx** [comment]
期货在zipline的平台已经逐步开始支持了，国内版本的暂时还没有研究，以后有对应的数据之后回考虑。先回把股票相关的内容完成，目前正在做的是机遇zipline框架的一套GUI环境，也就是类似可以在本地搭建一套类似quantopian的网页版本的环境，如果有合适的时机也考虑开源出来.. .

**Comment by Nonomeme** [comment]
@rainx  目前想做的事情跟您一样，也想基于zipline框架开发GUI环境，不知道现在有没有意向开源出来，或者有什么参考资料可以分享下？ 或者能否更新一下深入了解zipline 的那个blog，读了后感觉收获很多。谢谢大大。

祝好。

**Comment by rainx** [comment]
@Nonomeme 基于zipline的回测程序现在已经开发了，不过现在主要是面向学校的，数据源也是用的私有的数据源，所以暂时无法开放... 后续如果可能的话可能会考虑开源吧，这个还不确定， 那个文章后续有时间的时候会进行更新

**Comment by Nonomeme** [comment]
@rainx 我遇到个问题能请教下么？ 
下了zipline的源码，把zipline的路径添加到了sys.path中了，import zipline的时候报如下错误：
>>> import sys
>>> sys.path.append("/Users/apple/pinganProject/zipline")
>>> import zipline
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/apple/pinganProject/zipline/zipline/__init__.py", line 20, in <module>
    from . import data
  File "/Users/apple/pinganProject/zipline/zipline/data/__init__.py", line 1, in <module>
    from . import loader
  File "/Users/apple/pinganProject/zipline/zipline/data/loader.py", line 31, in <module>
    from zipline.utils.calendars import get_calendar
  File "/Users/apple/pinganProject/zipline/zipline/utils/calendars/__init__.py", line 16, in <module>
    from .trading_calendar import TradingCalendar
  File "/Users/apple/pinganProject/zipline/zipline/utils/calendars/trading_calendar.py", line 30, in <module>
    from zipline.utils.calendars._calendar_helpers import (
ImportError: No module named 'zipline.utils.calendars._calendar_helpers'

是因为_calendar_helpers类是私有类的原因么？该如何解决？

**Comment by rainx** [comment]
zipline有些模块用到了cython ，那部分需要使用c编译器单独编译之后才能运行..
